version: '3.5'

services:
    proxy:
        image: nginx
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - 80:80
        depends_on: 
            - backend
            - frontend
    db:
        image: postgres
        restart: unless-stopped
        environment: 
            - POSTGRES_PASSWORD=password
        volumes:
            - ./database:/var/lib/postgresql/data
    redis:
        build: ./redis
        ports: 
            - 6379:6379
        volumes:
            - ./redis/redis.conf:/redis.conf
    frontend:
        build: ./frontend
        environment: 
            - API_URL=http://localhost/api
        ports:
            - 5000:5000
    backend:
        build: ./backend
        environment: 
            - FRONT_URL=frontend
            - REDIS=redis
            - DB_HOST=db
            - DB_USERNAME=postgres
            - DB_PASSWORD=password
        ports:
            - 8000:8000
        depends_on: 
            - db