version: '3.5'

services:
    ml_frontend:
        build: ./ml-kurkkumopo-frontend
        ports:
            - 3000:3000
    ml_backend:
        build: ./ml-kurkkumopo-backend
        ports:
            - 5000:5000
        volumes:
            - model:/src/model
    ml_training:
        build: ./ml-kurkkumopo-training
        volumes:
            - model:/src/model
            - images:/src/imgs

volumes:
    model:
    images: