version: '3.5'

services:
    db:
        image: postgres
        restart: unless-stopped
        environment: 
            - POSTGRES_PASSWORD=password
    redis:
        build: ./redis
        ports: 
            - 6379:6379
        volumes:
            - ./redis/redis.conf:/redis.conf
    frontend:
        build: ./frontend
        environment: 
            - API_URL=http://localhost:8000
        ports:
            - 5000:5000
    backend:
        build: ./backend
        environment: 
            - FRONT_URL=http://localhost:5000
            - REDIS=redis
            - DB_HOST=db
            - DB_USERNAME=postgres
            - DB_PASSWORD=password
        ports:
            - 8000:8000
        depends_on: 
            - db