version: '3.5'

services:
    frontend:
        build: ./frontend
        environment: 
            - API_URL=http://localhost:8000
        ports:
            - 5000:5000
    backend:
        build: ./backend
        environment: 
            - FRONT_URL=http://localhost:5000
        ports:
            - 8000:8000